redis-ticketistas:
  ports:
  - 6379:6379/tcp
  - 16379:16379/tcp
  restart: always
  environment:
    SERVICE_NAME: 'redis-ticketistas'
    REDIS_PORT: '6379'
    ROOT_PASSWORD: 'password'
    REDIS_REPLICAS: 0
    DEBUG: 0
  image: reg.ticketistas.com:5000/t_redis
dbcluster-ticketistas:
  ports:
  - 33306:3306/tcp
  restart: always
  environment:
    SERVICE_NAME: 'dbcluster-ticketistas'
    PXC_SST_PASSWORD: 'SstPass'
    PXC_ROOT_PASSWORD: 'DiffPass'
    DB_USER: 'mysql'
    DB_USER_PASSWORD: 'mysql'
    PXC_INIT_SQL: 'tickets_db.sql'
  image: reg.ticketistas.com:5000/t_xtradb
  links:
  - redis-ticketistas
  volumes:
  - /dbdata/ticketistas/xtradb:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: lbl_database=true
app-ticketistas:
  ports:
  - 8080:8080/tcp
  - 9990:9990/tcp
  - 7600:7600/tcp
  - 8787:8787/tcp
  restart: always
  environment:
    SERVICE_NAME: 'app-ticketistas'
    APP_PORT: 8080
    ADMIN_PORT: 9900
    JGROUPS_PORT: 7600
    DB_SERVICE_NAME: 'dbcluster-ticketistas'
    DB_SERVICE_PORT: 3306
    MYSQL_DATABASE: 'Tickets'
    DB_USER: 'mysql'
    DB_USER_PASSWORD: 'mysql'
    DEBUG: 1
  image: reg.ticketistas.com:5000/t_asclient
  links:
  - dbcluster-ticketistas
  labels:
    io.rancher.scheduler.affinity:host_label: lbl_app=true
web-ticketistas:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  restart: always
  environment:
    MY_DEVPC_IP: '192.168.1.0/24'
    TICKETISTAS_REDIS_SERVICE: 'redis-ticketistas:6379'
    TICKETISTAS_APP_SERVICE: 'app-ticketistas:8080'
    NODES_ROUND_ROBIN: 1
  image: reg.ticketistas.com:5000/t_nginx
  links:
  - redis-ticketistas
  - app-ticketistas
  labels:
    io.rancher.scheduler.affinity:host_label: lbl_web_proxy=true
